TYPE MDSYS.SDO_POINT_TYPE GENERATE SDO_POINT_TYPE2 
TYPE MDSYS.SDO_ORDINATE_ARRAY GENERATE SDO_ORDINATE_ARRAY2
TYPE MDSYS.SDO_GEOMETRY GENERATE SDO_GEOMETRY 
TYPE MDSYS.SDO_TOPO_GEOMETRY GENERATE SDO_TOPO_GEOMETRY
TYPE MDSYS.SDO_TOPO_OBJECT GENERATE SDO_TOPO_OBJECT
TYPE MDSYS.SDO_TOPO_OBJECT_ARRAY GENERATE SDO_TOPO_OBJECT_ARRAY
TYPE MDSYS.SDO_DIM_ELEMENT GENERATE SDO_DIM_ELEMENT
TYPE MDSYS.SDO_DIM_ARRAY GENERATE SDO_DIM_ARRAY
