//
// Copyright (C) 2007 Refractions Research, Inc. 
// 
// This library is free software; you can redistribute it and/or
// modify it under the terms of version 2.1 of the GNU Lesser
// General Public License as published by the Free Software Foundation.
// 
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
// 
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
#include "stdafx.h"

#include "PostGisProvider.h"
#include "SchemaCapabilities.h"

#include <cassert>

namespace fdo { namespace postgis {

SchemaCapabilities::SchemaCapabilities()
{
}

SchemaCapabilities::~SchemaCapabilities()
{
}

///////////////////////////////////////////////////////////////////////////////
// FdoIDisposable interface
///////////////////////////////////////////////////////////////////////////////

void SchemaCapabilities::Dispose()
{
    delete this;
}

///////////////////////////////////////////////////////////////////////////////
// FdoISchemaCapabilities interface
///////////////////////////////////////////////////////////////////////////////

FdoClassType* SchemaCapabilities::GetClassTypes(FdoInt32& size)
{
    assert(!"NOT IMPLEMENTED");
    return NULL;
}

FdoDataType* SchemaCapabilities::GetDataTypes(FdoInt32& size)
{
    assert(!"NOT IMPLEMENTED");
    return NULL;
}

FdoInt64 SchemaCapabilities::GetMaximumDataValueLength(FdoDataType type)
{
    assert(!"NOT IMPLEMENTED");
    return 0;
}

FdoInt32 SchemaCapabilities::GetMaximumDecimalPrecision()
{
    assert(!"NOT IMPLEMENTED");
    return 0;
}

FdoInt32 SchemaCapabilities::GetMaximumDecimalScale()
{
    assert(!"NOT IMPLEMENTED");
    return 0;
}

FdoInt32 SchemaCapabilities::GetNameSizeLimit(FdoSchemaElementNameType name)
{
    assert(!"NOT IMPLEMENTED");
    return 0;
}

FdoString* SchemaCapabilities::GetReservedCharactersForName()
{
    assert(!"NOT IMPLEMENTED");
    return NULL;
}

FdoDataType* SchemaCapabilities::GetSupportedAutoGeneratedTypes(FdoInt32& size)
{
    assert(!"NOT IMPLEMENTED");
    return NULL;
}

FdoDataType* SchemaCapabilities::GetSupportedIdentityPropertyTypes(FdoInt32& size)
{
    assert(!"NOT IMPLEMENTED");
    return NULL;
}

bool SchemaCapabilities::SupportsAssociationProperties()
{
    assert(!"NOT IMPLEMENTED");
    return false;
}

bool SchemaCapabilities::SupportsAutoIdGeneration()
{
    assert(!"NOT IMPLEMENTED");
    return false;
}

bool SchemaCapabilities::SupportsCompositeId()
{
    assert(!"NOT IMPLEMENTED");
    return false;
}

bool SchemaCapabilities::SupportsCompositeUniqueValueConstraints()
{
    assert(!"NOT IMPLEMENTED");
    return false;
}

bool SchemaCapabilities::SupportsDataStoreScopeUniqueIdGeneration()
{
    assert(!"NOT IMPLEMENTED");
    return false;
}

bool SchemaCapabilities::SupportsDefaultValue()
{
    assert(!"NOT IMPLEMENTED");
    return false;
}

bool SchemaCapabilities::SupportsExclusiveValueRangeConstraints()
{
    assert(!"NOT IMPLEMENTED");
    return false;
}

bool SchemaCapabilities::SupportsInclusiveValueRangeConstraints()
{
    assert(!"NOT IMPLEMENTED");
    return false;
}

bool SchemaCapabilities::SupportsInheritance()
{
    assert(!"NOT IMPLEMENTED");
    return false;
}

bool SchemaCapabilities::SupportsMultipleSchemas()
{
    assert(!"NOT IMPLEMENTED");
    return false;
}

bool SchemaCapabilities::SupportsNetworkModel()
{
    assert(!"NOT IMPLEMENTED");
    return false;
}

bool SchemaCapabilities::SupportsNullValueConstraints()
{
    assert(!"NOT IMPLEMENTED");
    return false;
}

bool SchemaCapabilities::SupportsObjectProperties()
{
    assert(!"NOT IMPLEMENTED");
    return false;
}

bool SchemaCapabilities::SupportsSchemaModification()
{
    assert(!"NOT IMPLEMENTED");
    return false;
}

bool SchemaCapabilities::SupportsSchemaOverrides()
{
    assert(!"NOT IMPLEMENTED");
    return false;
}

bool SchemaCapabilities::SupportsUniqueValueConstraints()
{
    assert(!"NOT IMPLEMENTED");
    return false;
}

bool SchemaCapabilities::SupportsValueConstraintsList()
{
    assert(!"NOT IMPLEMENTED");
    return false;
}

}} // namespace fdo::postgis
